import { Buffer } from 'node:buffer'

export interface ExportSection {
  title: string
  rows: Array<{ label: string; value: string | number }>
}

const csvEscape = (value: string | number) => {
  const stringValue = String(value)
  return /[",\n\r]/.test(stringValue) ? `"${stringValue.replace(/"/g, '""')}"` : stringValue
}

export const buildCsvDocument = (headers: string[], rows: Array<Array<string | number>>) => {
  const lines = [headers, ...rows].map((row) => row.map(csvEscape).join(','))
  return Buffer.from(`${lines.join('\n')}\n`, 'utf8')
}

const pdfEscape = (value: string) =>
  value
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')

const wrapPdfLine = (value: string, maxLength = 92) => {
  if (value.length <= maxLength) {
    return [value]
  }

  const words = value.split(/\s+/)
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const next = current ? `${current} ${word}` : word
    if (next.length > maxLength && current) {
      lines.push(current)
      current = word
    } else {
      current = next
    }
  }

  if (current) {
    lines.push(current)
  }

  return lines
}

export const buildPdfSummaryDocument = (title: string, sections: ExportSection[]) => {
  const lines = [title, 'Generated by Pulse', '']

  for (const section of sections) {
    lines.push(section.title)
    for (const row of section.rows) {
      lines.push(`${row.label}: ${row.value}`)
    }
    lines.push('')
  }

  const contentLines = [
    'BT',
    '/F1 16 Tf',
    '50 742 Td',
    `(${pdfEscape(lines[0] || 'Pulse report')}) Tj`,
    '/F1 10 Tf',
  ]

  for (const line of lines.slice(1)) {
    for (const wrapped of wrapPdfLine(line)) {
      contentLines.push('0 -16 Td')
      contentLines.push(`(${pdfEscape(wrapped)}) Tj`)
    }
  }

  contentLines.push('ET')
  const content = `${contentLines.join('\n')}\n`
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}endstream`,
  ]

  const chunks = [`%PDF-1.4\n%\xE2\xE3\xCF\xD3\n`]
  const offsets = [0]

  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(chunks.join(''), 'binary'))
    chunks.push(`${index + 1} 0 obj\n${objects[index]}\nendobj\n`)
  }

  const xrefOffset = Buffer.byteLength(chunks.join(''), 'binary')
  chunks.push(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`)
  for (let index = 1; index <= objects.length; index += 1) {
    chunks.push(`${String(offsets[index]).padStart(10, '0')} 00000 n \n`)
  }
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`)

  return Buffer.from(chunks.join(''), 'binary')
}
